//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboSnip.WPF.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TurboSnip.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        public static string Help_Title
        {
            get
            {
                return ResourceManager.GetString("Help_Title", resourceCulture);
            }
        }

        public static string Help_Features_Title
        {
            get
            {
                return ResourceManager.GetString("Help_Features_Title", resourceCulture);
            }
        }

        public static string Help_Privacy
        {
            get
            {
                return ResourceManager.GetString("Help_Privacy", resourceCulture);
            }
        }

        public static string Help_LiveCapture
        {
            get
            {
                return ResourceManager.GetString("Help_LiveCapture", resourceCulture);
            }
        }

        public static string Help_Performance
        {
            get
            {
                return ResourceManager.GetString("Help_Performance", resourceCulture);
            }
        }

        public static string Help_Usage_Title
        {
            get
            {
                return ResourceManager.GetString("Help_Usage_Title", resourceCulture);
            }
        }

        public static string Help_Step1
        {
            get
            {
                return ResourceManager.GetString("Help_Step1", resourceCulture);
            }
        }

        public static string Help_Step2
        {
            get
            {
                return ResourceManager.GetString("Help_Step2", resourceCulture);
            }
        }

        public static string Help_Step3
        {
            get
            {
                return ResourceManager.GetString("Help_Step3", resourceCulture);
            }
        }

        public static string Help_Step4
        {
            get
            {
                return ResourceManager.GetString("Help_Step4", resourceCulture);
            }
        }

        public static string Help_GotIt
        {
            get
            {
                return ResourceManager.GetString("Help_GotIt", resourceCulture);
            }
        }

        public static string About_Title
        {
            get
            {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }

        public static string About_DesignedBy
        {
            get
            {
                return ResourceManager.GetString("About_DesignedBy", resourceCulture);
            }
        }

        public static string About_PoweredBy
        {
            get
            {
                return ResourceManager.GetString("About_PoweredBy", resourceCulture);
            }
        }

        public static string About_Close
        {
            get
            {
                return ResourceManager.GetString("About_Close", resourceCulture);
            }
        }
    }
}
